language: python
python:
  - "3.8"
  - "3.9"

# command to install dependencies
install:
  - "pip install ."
  - pip install coveralls

# command to run tests
script: nosetests --with-coverage --cover-erase --cover-package=sourceparse

after_success:
  - coveralls
